# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole projects, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'




## => Site Settings
##############################
url: https://niccolozanotti.com
baseurl: /
title: Niccolò Zanotti
description: >
    My personal website.


## => Language and Timezone
##############################
lang: en
timezone: Europe/Rome


## => Author and Social
##############################
author:
  name: Niccolò Zanotti
  email: hello@niccolozanotti.com
  # Social media profiles
  github:  niccolozanotti
  linkedin: niccolo-zanotti
  bluesky: niccolozanotti.com
  mastodon: niccolozanotti
#  X: niccolozanotti


## => GitHub Repository (if the site is hosted by GitHub)
##############################
repository: niccolozanotti/my-website
repository_tree: master


## => Paths
##############################
paths:
  root: /
  home: /projects
  archive: /projects/archive.html
  rss:  /feed.xml


## => Post
##############################
## excerpt
excerpt_separator: <!--more-->

## license
license: CC-BY-4.0


## => Paginate
##############################
paginate: 7
paginate_path: /projects/page:num


## => Comments
##############################
# comments:
#   provider: disqus
#   disqus:
#     shortname: niccolozanotti


## => Pageview
##############################
pageview:
  provider: leancloud
  leancloud:
    app_id: 
    app_key: 
    app_class: 


## => Analytics
##############################
analytics:
  provider: google
  google:
    tracking_id: 


## => Build
##############################
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true


## => Plugins
##############################
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji


## => Server
##############################
server_url: "0.0.0.0"
port: 4001